<?xml version="1.0" ?>
<robot name="turtlebot3_waffle" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:include filename="$(find kasva_description)/urdf/common_properties.xacro"/>
  <xacro:include filename="$(find kasva_description)/urdf/kasva.gazebo.xacro"/>

  <xacro:property name="r200_cam_rgb_px" value="0.05"/>
  <xacro:property name="r200_cam_rgb_py" value="0.18"/>
  <xacro:property name="r200_cam_rgb_pz" value="0.13"/>
  <xacro:property name="r200_cam_depth_offset" value="0.1"/>

  <link name="base_footprint"/>

  <joint name="base_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link" />
    <origin xyz="0 0 0.10" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="-0.64 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://kasva_description/meshes/bases/waffle_base.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="light_black"/>
    </visual>

    <collision>
      <origin xyz="-0.64 0 0.47" rpy="0 0 0"/>
      <geometry>
        <box size="2.66 2.66 0.94"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="13.729096"/>
      <inertia ixx="8.7002718e-02" ixy="-4.7576583e-04" ixz="1.1160499e-03"
               iyy="8.6195418e-02" iyz="-3.5422299e-05"
               izz="1.4612727e-01" />
    </inertial>
  </link>

  <joint name="wheel_left_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_left_link"/>
    <origin xyz="0.0 1.44 0.23" rpy="-1.57 0 0"/>
    <axis xyz="0 0 10"/>
  </joint>

  <link name="wheel_left_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://kasva_description/meshes/wheels/left_tire.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.18" radius="0.33"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-04" ixy="-4.2369783e-10" ixz="-5.9381719e-08"
               iyy="1.1192413e-04" iyz="-1.4400107e-10"
               izz="2.0712558e-04" />
      </inertial>
  </link>
<!-- -->
  <joint name="wheel_right_joint" type="continuous">
    <parent link="base_link"/>
    <child link="wheel_right_link"/>
    <origin xyz="0.0 -1.44 0.23" rpy="-1.57 0 0"/>
    <axis xyz="0 0 10"/>
  </joint>

  <link name="wheel_right_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <mesh filename="package://kasva_description/meshes/wheels/right_tire.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.18" radius="0.33"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="2.8498940e-01" />
      <inertia ixx="1.1175580e-04" ixy="-4.2369783e-10" ixz="-5.9381719e-08"
               iyy="1.1192413e-04" iyz="-1.4400107e-10"
               izz="2.0712558e-04" />
      </inertial>
  </link>

  <joint name="caster_back_right_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_right_link"/>
    <origin xyz="-1.77 -0.64 -0.04" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_right_link">
    <collision>
      <origin xyz="0 0.01 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.30 0.09 0.20"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.05" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>
  </link>

  <joint name="caster_back_left_joint" type="fixed">
    <parent link="base_link"/>
    <child link="caster_back_left_link"/>
    <origin xyz="-1.77 0.64 -0.04" rpy="-1.57 0 0"/>
  </joint>

  <link name="caster_back_left_link">
    <collision>
      <origin xyz="0 0.01 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.30 0.09 0.20"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 0" />
      <mass value="0.05" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0.0 0 0.68" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="-0.64 0 1.22" rpy="0 0 0"/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://kasva_description/meshes/sensors/lds.stl" scale="0.01 0.01 0.01"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.15 0 -0.065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.315" radius="0.55"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="1.14" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>
  </link>

  <joint name="camera_joint" type="fixed">
    <origin xyz="0.64 -0.65 0.94" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
     <origin xyz="0 0 0" rpy="1.57 0 1.57"/>
      <geometry>
       <mesh filename="package://kasva_description/meshes/sensors/r200.dae" />
      </geometry>
    </visual>
    <collision>
      <origin xyz="0.03 0.65 0.07" rpy="0 0 0"/>
      <geometry>
        <box size="0.12 1.32 0.20"/>
      </geometry>
    </collision>

    <!-- This inertial field needs doesn't contain reliable data!! -->
<!--   <inertial>
      <mass value="0.564" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.003881243" ixy="0.0" ixz="0.0"
               iyy="0.000498940" iyz="0.0"
               izz="0.003879257" />
    </inertial>-->
  </link>

  <joint name="camera_rgb_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_rgb_frame"/>
  </joint>
  <link name="camera_rgb_frame"/>

  <joint name="camera_rgb_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-15.7 0 -15.7"/>
    <parent link="camera_rgb_frame"/>
    <child link="camera_rgb_optical_frame"/>
  </joint>
  <link name="camera_rgb_optical_frame"/>

  <joint name="camera_depth_joint" type="fixed">
    <origin xyz="${r200_cam_rgb_px} ${r200_cam_rgb_py + r200_cam_depth_offset} ${r200_cam_rgb_pz}" rpy="0 0 0"/>
    <parent link="camera_link"/>
    <child link="camera_depth_frame"/>
  </joint>
  <link name="camera_depth_frame"/>

  <joint name="camera_depth_optical_joint" type="fixed">
    <origin xyz="0 0 0" rpy="-1.57 0 -1.57"/>
    <parent link="camera_depth_frame"/>
    <child link="camera_depth_optical_frame"/>
  </joint>
  <link name="camera_depth_optical_frame"/>

</robot>
